project_id = "pajepyomtenbnttzahsv"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-category-password-otp]
verify_jwt = true

[functions.verify-category-password-otp]
verify_jwt = true
